<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>This year's wrapped!</title>

        <link rel="stylesheet" href="<?= $resource ('/fontawesome/css/all.min.css') ?>">
        <link rel="stylesheet" href="<?= $resource ('/bootstrap/css/bootstrap.min.css') ?>">
        <link rel="stylesheet" href="<?= $resource ('main.css') ?>">
        <script src="<?= $resource ('/jquery/jquery-3.4.1.min.js') ?>"></script>
        <script src="<?= $resource ('/bootstrap/js/bootstrap.min.js') ?>"></script>
    </head>
    <body class="pt-3">
        <div class="container">
            <?php $showblock ('content') ?>
        </div>
    </body>
</html>